# Smart Sales Data Analyzer (NumPy v1)

## Projenin Amacı
Bu projenin amacı, NumPy kullanarak 7 günlük satış verisini analiz etmek ve
çok boyutlu array yapısını gerçek bir senaryo üzerinden öğrenmektir.

## NumPy Neden Kullanılır?
- Hızlı ve verimli sayısal işlemler için
- Çok boyutlu veri yapılarıyla çalışmak için
- Python döngülerine alternatif vektörel işlemler yapmak için

## Kullanılan NumPy Konuları
- NumPy array oluşturma
- Array özellikleri (shape, ndim, dtype)
- Indexing & slicing
- Temel NumPy metodları
- axis kullanımı
- reshape, transpose, flatten

In [7]:
## 1. NumPy Import & Veri Oluşturma
import numpy as np

# 7 gün x 5 ürün satış verisi
sales_data = np.array([
    [120, 80, 100, 90, 110],
    [130, 85, 105, 95, 115],
    [125, 78, 98, 88, 108],
    [140, 90, 120, 100, 130],
    [150, 95, 125, 105, 135],
    [160, 100, 130, 110, 140],
    [155, 98, 128, 108, 138]
])

sales_data

array([[120,  80, 100,  90, 110],
       [130,  85, 105,  95, 115],
       [125,  78,  98,  88, 108],
       [140,  90, 120, 100, 130],
       [150,  95, 125, 105, 135],
       [160, 100, 130, 110, 140],
       [155,  98, 128, 108, 138]])

In [17]:
## 2. Array Özellikleri
print("Dizi Boyutu:", sales_data.shape)
print("Boyut Sayısı (ndim):", sales_data.ndim)
print("Veri Tipi:", sales_data.dtype)
print("Toplam Eleman Sayısı:", sales_data.size)

Dizi Boyutu: (7, 5)
Boyut Sayısı (ndim): 2
Veri Tipi: int64
Toplam Eleman Sayısı: 35


In [10]:
## 3. Indexing & Slicing
# 3. günün satışları (index 2)
third_day_sales = sales_data[2]
print("3. gün satışları:", third_day_sales)

# 2. ürünün haftalık satışları (index 1)
second_product_weekly = sales_data[:, 1]
print("2. ürün haftalık satış:", second_product_weekly)

# İlk 3 gün
first_three_days = sales_data[:3]
print("İlk 3 gün:\n", first_three_days)

3. gün satışları: [125  78  98  88 108]
2. ürün haftalık satış: [ 80  85  78  90  95 100  98]
İlk 3 gün:
 [[120  80 100  90 110]
 [130  85 105  95 115]
 [125  78  98  88 108]]


In [11]:
## 4. Temel NumPy Methodları
total_sales = sales_data.sum()
daily_average = sales_data.mean()
max_sale = sales_data.max()
min_sale = sales_data.min()

print("Toplam haftalık satış:", total_sales)
print("Günlük ortalama satış:", daily_average)
print("En yüksek satış:", max_sale)
print("En düşük satış:", min_sale)

Toplam haftalık satış: 3984
Günlük ortalama satış: 113.82857142857142
En yüksek satış: 160
En düşük satış: 78


In [14]:
## 5. Axis Kullanımı
# Gün bazlı toplam satış (axis 1 satırlar (günler) üstünde çalışır)
daily_totals = sales_data.sum(axis=1)
print("Gün bazlı toplam satış:", daily_totals)

# Ürün bazlı toplam satış (axis 2 sütunlar (ürünler) üstünde çalışır)
product_totals = sales_data.sum(axis=0)
print("Ürün bazlı toplam satış:", product_totals)

Gün bazlı toplam satış: [500 530 497 580 610 640 627]
Ürün bazlı toplam satış: [980 626 806 696 876]


In [15]:
## 6. Numpy Dizi Methodları
# reshape
reshaped_data = sales_data.reshape(5, 7)
print("Reshape (5x7):\n", reshaped_data)
# Veriyi yeniden şekillendirme (Örn: Toplam 35 veriyi 5x7 yapma - farklı bir görünüm)

# transpose
transposed_data = sales_data.T
print("Transpose:\n", transposed_data)
# Matrisi tersine çevirme (Ürünleri satır, günleri sütun yapma)

# flatten
flattened_data = sales_data.flatten()
print("Flatten:\n", flattened_data)
# Veriyi 1x35 boyutuna düzleştirme (Analiz sonrası raporlama için)

Reshape (5x7):
 [[120  80 100  90 110 130  85]
 [105  95 115 125  78  98  88]
 [108 140  90 120 100 130 150]
 [ 95 125 105 135 160 100 130]
 [110 140 155  98 128 108 138]]
Transpose:
 [[120 130 125 140 150 160 155]
 [ 80  85  78  90  95 100  98]
 [100 105  98 120 125 130 128]
 [ 90  95  88 100 105 110 108]
 [110 115 108 130 135 140 138]]
Flatten:
 [120  80 100  90 110 130  85 105  95 115 125  78  98  88 108 140  90 120
 100 130 150  95 125 105 135 160 100 130 110 140 155  98 128 108 138]


In [16]:
### Genel Özet
best_selling_product = product_totals.argmax() + 1
best_day = daily_totals.argmax() + 1

print(f"Toplam haftalık satış: {total_sales}")
print(f"En çok satan ürün: Ürün {best_selling_product}")
print(f"En iyi gün: Gün {best_day}")

Toplam haftalık satış: 3984
En çok satan ürün: Ürün 1
En iyi gün: Gün 6
