# Smart Performance Analytics System (NumPy – General Review)

## Amaç
Bu projenin amacı, NumPy kullanarak çok boyutlu performans verisini
etkili bir şekilde analiz etmektir.

## Neden NumPy?
- Hızlıdır (vektörel işlemler)
- Çok boyutlu veri (matrix) ile çalışmayı kolaylaştırır
- Döngü yazmadan toplu hesaplama yapmamızı sağlar

## Kapsanan Konular
- NumPy array & matrix
- Indexing & slicing
- Vektörel işlemler
- Axis kullanımı
- Array metodları

In [1]:
# 2. Numpy Import & Veri Oluşturma

import numpy as np

# 8 çalışan x 6 ay performans verisi (50–100 arası)
performance = np.random.randint(50, 101, size=(8, 6))

performance

array([[ 98,  82,  63,  93,  79,  82],
       [ 88,  99,  83,  93,  94,  87],
       [100,  72,  62,  92,  96,  67],
       [ 52,  80,  74,  93,  97,  53],
       [ 81,  59,  66,  74,  83,  66],
       [ 70,  84,  85,  89,  61,  85],
       [ 57,  92,  56,  85,  73,  96],
       [ 79,  82,  74,  87,  84,  51]])

In [2]:
# 3. Array Özellikleri

print("Shape:", performance.shape)
print("Boyut (ndim):", performance.ndim)
print("Veri tipi:", performance.dtype)
print("Toplam eleman:", performance.size)

Shape: (8, 6)
Boyut (ndim): 2
Veri tipi: int64
Toplam eleman: 48


In [3]:
# 4. NumPy İndeksleme

# İlk çalışanın tüm ayları
first_employee = performance[0]
print("İlk çalışan:", first_employee)

# Son ayın tüm çalışanları
last_month = performance[:, -1]
print("Son ay:", last_month)

# İlk 3 çalışanın ilk 2 ayı
subset = performance[:3, :2]
print("Alt veri:\n", subset)

İlk çalışan: [98 82 63 93 79 82]
Son ay: [82 87 67 53 66 85 96 51]
Alt veri:
 [[ 98  82]
 [ 88  99]
 [100  72]]


In [4]:
# 5. Matrix İndeksleme

# 4. çalışanın 3. ay performansı
specific_score = performance[3, 2]
print("Belirli skor:", specific_score)

# Alt matris (çalışan 2–5, ay 1–3)
sub_matrix = performance[1:5, 1:4]
print("Sub-matrix:\n", sub_matrix)

Belirli skor: 74
Sub-matrix:
 [[99 83 93]
 [72 62 92]
 [80 74 93]
 [59 66 74]]


In [7]:
# 6. NumPy Operasyonlar

# Tüm skorlara +5 ekle
boosted_scores = performance + 5
print("Boosted Scores:\n", boosted_scores)

# 100 üzerinden normalize et
normalized_scores = boosted_scores / 100
print("Normalized Scores:\n", normalized_scores)

# Ay 1 ve Ay 2 karşılaştırması
comparison = performance[:, 0] > performance[:, 1]

print("Ay1 > Ay2 karşılaştırması:\n", comparison)

Boosted Scores:
 [[103  87  68  98  84  87]
 [ 93 104  88  98  99  92]
 [105  77  67  97 101  72]
 [ 57  85  79  98 102  58]
 [ 86  64  71  79  88  71]
 [ 75  89  90  94  66  90]
 [ 62  97  61  90  78 101]
 [ 84  87  79  92  89  56]]
Normalized Scores:
 [[1.03 0.87 0.68 0.98 0.84 0.87]
 [0.93 1.04 0.88 0.98 0.99 0.92]
 [1.05 0.77 0.67 0.97 1.01 0.72]
 [0.57 0.85 0.79 0.98 1.02 0.58]
 [0.86 0.64 0.71 0.79 0.88 0.71]
 [0.75 0.89 0.9  0.94 0.66 0.9 ]
 [0.62 0.97 0.61 0.9  0.78 1.01]
 [0.84 0.87 0.79 0.92 0.89 0.56]]
Ay1 > Ay2 karşılaştırması:
 [ True False  True False  True False False False]


In [8]:
# 7. NumPy Metodları
# axis=1 -> Satır boyunca (Çalışan bazlı)
employee_avg = performance.mean(axis=1)

# axis=0 -> Sütun boyunca (Ay bazlı)
month_avg = performance.mean(axis=0)

print("Çalışan ortalamaları:", employee_avg)
print("Ay ortalamaları:", month_avg)

print("En yüksek performans:", performance.max())
print("En düşük performans:", performance.min())

Çalışan ortalamaları: [82.83333333 90.66666667 81.5        74.83333333 71.5        79.
 76.5        76.16666667]
Ay ortalamaları: [78.125 81.25  70.375 88.25  83.375 73.375]
En yüksek performans: 100
En düşük performans: 51


In [9]:
# 8. Numpy Dizi Methodları
# Transpose (aylar ↔ çalışanlar)
transposed = performance.transpose()

# Tek boyuta indirgeme
flat_data = performance.flatten()

print("Transpose shape:", transposed.shape)
print("Flatten uzunluk:", len(flat_data))

Transpose shape: (6, 8)
Flatten uzunluk: 48


In [10]:
# Genel Performans Özeti
best_employee = np.argmax(employee_avg) + 1
best_month = np.argmax(month_avg) + 1
overall_avg = performance.mean()

print(f"En başarılı çalışan: Çalışan {best_employee}")
print(f"En yüksek ay ortalaması: Ay {best_month}")
print(f"Genel ortalama performans: {overall_avg:.2f}")

En başarılı çalışan: Çalışan 2
En yüksek ay ortalaması: Ay 4
Genel ortalama performans: 79.12
