In [1]:
import numpy as np

## numpy array

In [2]:
# array (diziler numpy dizileri) (Tek boyutlu ya da iki boyutlu diziler, matrix şeklinde.
# listelerle olan ilişkisi 

In [3]:
benimListem = [20,30,40]

In [4]:
type(benimListem)

list

In [5]:
np.array(benimListem)

array([20, 30, 40])

In [6]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [8]:
matrixListesi[1][0]

20

In [9]:
np.array(matrixListesi) # iki boyutlu gösterir. kendi içinde buluduğumuz durumu daha iyi anlarız.

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [10]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,20,2) # 3. sayı step size atlayarak gidiyor.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros

In [16]:
np.zeros(5) # içinde sıfır olan dizi oluşturuyor.

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((9,9)) # tuple gibi yazmamış gerekiyor

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [28]:
np.linspace(0,10,100) 

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
# eşit olarak boyutlandırılmış aralık bırakılmış şekilde dizi oluşturuyor. 
# Evenly space

## eye

In [29]:
# identity matrix 

In [31]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [33]:
np.random.randn(4) #ramdn (nunmpy dizisi döndürüyor)

array([-0.6149787 ,  0.5554074 ,  1.18581841,  1.10961289])

In [34]:
np.random.randn(4,4)

array([[-2.06822917, -0.16658742, -0.53416944, -0.66039185],
       [ 0.12925982, -0.31072077,  0.29115232,  0.80778403],
       [-1.51561947,  0.4688808 ,  0.97733697,  0.95666944],
       [ 0.56904282,  0.56904054, -0.90530558, -0.78486148]])

In [35]:
np.random.randint(1,10) # son rakamı almıyor

8

In [37]:
np.random.randint(1,100,5) # (kaçtan, kaça, kaç rakam)

array([ 4,  3, 51, 46, 41], dtype=int32)

In [38]:
# eşitliğe eşitliyeibliriz. Değişkene eşitleyebiliriz.

In [39]:
benimNumpyDizim = np.arange(30)

In [40]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [41]:
benimRandomDizim = np.random.randint(0,100,30)

In [42]:
benimRandomDizim

array([26, 99, 20, 34, 65, 79, 49, 15, 73, 39, 61, 25, 35, 65, 24, 87, 83,
       86, 35, 56, 28, 42, 39, 27, 19, 52, 91, 19, 23, 98], dtype=int32)

# numpy dizi methodlar

In [43]:
benimNumpyDizim.reshape(5,6) # içinde *kaç rakam* varsa ona göre row oluşturur. ya da column oluşturur.

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [44]:
benimNumpyDizim.max()

np.int64(29)

In [45]:
benimRandomDizim.max()

np.int32(99)

In [47]:
benimRandomDizim.argmax()

np.int64(1)

In [48]:
benimRandomDizim.argmin()

np.int64(7)

In [49]:
# attributelari özellikleri

In [50]:
benimRandomDizim.shape #method değil fonksiyon olduğu için sonuna parantez koymuyoruz.

(30,)

In [51]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [52]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [53]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])