In [1]:
import numpy as np

In [2]:
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[5]

np.int64(5)

In [6]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [7]:
benimDizim[3:8] = -5

In [8]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# dizin içindeki elemanları değiştirebiliriz.

In [10]:
baskaDizi = np.arange(0,24)

In [11]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [17]:
slicingDizisi = baskaDizi[4:9]

In [18]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [19]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
slicingDizisi[:] = 700 # tek tek bütün elemanları 700 e eşitliyor.

In [22]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [23]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [24]:
# numpy dizilerinde bir dizinin içinde bir parçayı alıp işlersen bütünde değişir.


In [25]:
ornekDizi = np.arange(0,24)

In [26]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [28]:
ornekDiziKopyasi

NameError: name 'ornekDiziKopyasi' is not defined

In [29]:
# vektörel işlem tek boyutlu dizilerle işlem yaptık
# ama iki boyutlu yani matrixlerle çalışabiliriz.

## matrix

In [30]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [31]:
benimMatrixDizim = np.array(benimListem)

In [32]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [33]:
benimMatrixDizim[0] # ilk yazdığımız şey sırayı ikincisi kolonu verir.

array([10, 20, 30])

In [34]:
benimMatrixDizim[1][2]

np.int64(40)

In [35]:
benimMatrixDizim[1,2] # ilk eleman 0,1,2,3, diye gider.

np.int64(40)

In [39]:
benimMatrixDizim[0:,2] # : sırayla getirir.

array([30, 40, 60])

In [40]:
benimMatrixDizim[2:,2:]

array([[60]])

In [41]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [42]:
yeniMatrix = np.array(yeniListe)

In [43]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
yeniMatrix[[4,2,0]] # fancy index

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## operasyonlar

In [45]:
# toplama çıkarma

In [48]:
yeniBirDizi = np.random.randint(1,100,20)

In [49]:
yeniBirDizi

array([99, 79, 90, 92,  3, 88, 51, 23, 37, 24, 80,  3, 92, 47, 66,  2, 96,
       77, 38, 84], dtype=int32)

In [50]:
yeniBirDizi > 24

array([ True,  True,  True,  True, False,  True,  True, False,  True,
       False,  True, False,  True,  True,  True, False,  True,  True,
        True,  True])

In [51]:
# tek tek boolean olarak döndürüyor.

In [52]:
sonucDizi = yeniBirDizi > 24

In [54]:
sonucDizi

array([ True,  True,  True,  True, False,  True,  True, False,  True,
       False,  True, False,  True,  True,  True, False,  True,  True,
        True,  True])

In [55]:
yeniBirDizi

array([99, 79, 90, 92,  3, 88, 51, 23, 37, 24, 80,  3, 92, 47, 66,  2, 96,
       77, 38, 84], dtype=int32)

In [56]:
yeniBirDizi[yeniBirDizi > 24]

array([99, 79, 90, 92, 88, 51, 37, 80, 92, 47, 66, 96, 77, 38, 84],
      dtype=int32)

In [57]:
sonDizi = np.arange(0,24)

In [58]:
sonDizi 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [59]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [60]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [61]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [62]:
np.sqrt(sonDizi) # karekökü almak

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [63]:
np.max(sonDizi)

np.int64(23)

In [65]:
np.min(sonDizi)

np.int64(0)